import { getSystemUrl } from './utils';

const { base_url, web_name, socket_url } = getSystemUrl(__KG_API_ENV__);

export default {
  socket_url,
  base_url,
  web_name,
  videoAuthConcat: [
    {
      text: '客服电话1',
      account: '123',
    },
    {
      text: '客服电话2',
      account: '1234',
    },
    {
      text: '客服电话3',
      account: '1235',
    },
    {
      text: '客服QQ1',
      account: '312321312321',
    },
  ],
  web_sub_title: 'Itunes & 礼品卡 在线交易平台',
  language: {
    zh_CN: '简体中文',
    en_GB: 'English',
  },
  payments: {
    wechat: '微信支付',
    alipay: '支付宝',
    bank: '银行卡',
    site: '站内转账',
  },
  ad_type: {
    1: '买入',
    2: '出售',
  },
  auth_status: {},
  ad_status: {
    1: '已发布',
    2: '已暂停',
    3: '已冻结',
    4: '已取消',
    5: '已删除',
  },
  order_status: {
    1: '打开中',
    2: '待查收',
    3: '保障中',
    4: '申述中',
    5: '已完成',
    6: '已取消',
  },
  goods_type: {
    1: 'itunes',
    2: '礼品卡',
  },
  trans_term_status: {
    1: '未通过',
    2: '审核中',
    3: '已通过',
  },
  message_type_zh_CN: {
    1: '系统资讯',
    11: '您的身份认证，后台已审核通过',
    12: '您的身份认证，后台审核未通过, 原因： %reason%',
    21: '您提交的支付方式，后台认证通过',
    22: '您提交的支付方式，后台认证不通过, 原因： %reason%',
    31: '提现成功',
    32: '提现失败',
    33: '充值成功',
    34: '充值失败',
    41: '交易条款审核通过',
    42: '交易条款审核不通过, 原因： %reason%',
    101: '【%order_no%】您有新的订单',
    102: '【%order_no%】您的交易订单，已确认释放',
    103: '【%order_no%】对方已上传凭证成功',
    104: '【%order_no%】您有新的交易消息',
    105: '【%order_no%】你有新的申述',
    106: '【%order_no%】订单保障时间已到，订单自动取消',
    107: '【%order_no%】客服处理申述，申述结果 完成订单',
    108: '【%order_no%】客服处理申述，申述结果 取消订单, 原因： %reason%',
  },
  message_type_en_GB: {
    1: '系统资讯',
    11: '您的身份认证，后台已审核通过',
    12: '您的身份认证，后台审核未通过, 原因： %reason%',
    21: '您提交的支付方式，后台认证通过',
    22: '您提交的支付方式，后台认证不通过, 原因： %reason%',
    31: '提现成功',
    32: '提现失败',
    33: '充值成功',
    34: '充值失败',
    41: '交易条款审核通过',
    42: '交易条款审核不通过, 原因： %reason%',
    101: '【%order_no%】您有新的订单',
    102: '【%order_no%】您的交易订单，已确认释放',
    103: '【%order_no%】对方已上传凭证成功',
    104: '【%order_no%】您有新的交易消息',
    105: '【%order_no%】你有新的申述',
    106: '【%order_no%】订单保障时间已到，订单自动取消',
    107: '【%order_no%】客服处理申述，申述结果 完成订单',
    108: '【%order_no%】客服处理申述，申述结果 取消订单, 原因： %reason%',
  },
  cardPwdType: {
    // 1: '密码',
    // 2: '图片',
    // 3: '密码和图片',
    1: '有卡密',
    2: '有卡图',
    3: '有图有卡密',
  },
  tradeType: {
    1: '交易',
    2: '充值',
    3: '提现',
  },
};
