import { getSystemUrl } from './utils';

const { base_url, web_name, socket_url } = getSystemUrl(__KG_API_ENV__);

export default {
  socket_url,
  base_url,
  web_name,
  videoAuthConcat: [
    {
      text: '客服电话1',
      account: '123',
    },
    {
      text: '客服电话2',
      account: '1234',
    },
    {
      text: '客服电话3',
      account: '1235',
    },
    {
      text: '客服QQ1',
      account: '312321312321',
    },
  ],
  web_sub_title: 'Itunes & 礼品卡 在线交易平台',
  language: {
    zh_CN: '简体中文',
    en_GB: 'English',
  },
  payments: {
    wechat: '微信支付',
    alipay: '支付宝',
    bank: '银行卡',
    site: '站内转账',
  },
  ad_type: {
    1: '买入',
    2: '出售',
  },
  auth_status: {},
  ad_status: {
    1: '已发布',
    2: '已暂停',
    3: '已冻结',
    4: '已取消',
    5: '已删除',
  },
  order_status: {
    1: '打开中',
    2: '待查收',
    3: '保障中',
    4: '申述中',
    5: '已完成',
    6: '已取消',
  },
  goods_type: {
    1: 'itunes',
    2: '礼品卡',
  },
  trans_term_status: {
    1: '未通过',
    2: '审核中',
    3: '已通过',
  },
  message_type_zh_CN: {
    1: '系统资讯',
    11: '您的{auth_type}已通过',
    12: '您的{auth_type}未通过',
    21: '您的{payment_method}{account}审核已通过',
    22: '您的{payment_method}{account}审核未通过',
    31: '您的提现请求审核已通过',
    32: '您的提现请求审核未通过',
    33: '您的充值请求审核已通过',
    34: '您的充值请求审核未通过',
    41: '交易条款"{title}"审核已通过',
    42: '交易条款"{title}"审核未通过',
    101: '{dealer}向您出售{goods_type}',
    102: '{dealer}向您购买{goods_type}',
    103: '您有新的订单待查收，请在10分钟内确认',
    104: '您有新的订单消息',
    105: '订单{order_no}超出保障时间，已自动释放',
    106: '{dealer}已取消订单',
    107: '{dealer}发起了申诉',
    108: '您有新的申诉消息',
    109: '客服已释放订单{order_no}',
    110: '客服已取消订单{order_no}',
    111: '{dealer}已释放订单{order_no}',
    112: '订单{order_no}超出查收时间，已自动取消',
    113: '订单{order_no}超出发卡时间，已自动取消',
    114: '{dealer}已查收，请耐心等待释放',
  },
  message_type_en_GB: {
    1: '系统资讯',
    11: '您的{auth_type}已通过',
    12: '您的{auth_type}未通过',
    21: '您的{payment_method}{account}审核已通过',
    22: '您的{payment_method}{account}审核未通过',
    31: '您的提现请求审核已通过',
    32: '您的提现请求审核未通过',
    33: '您的充值请求审核已通过',
    34: '您的充值请求审核未通过',
    41: '交易条款"{title}"审核已通过',
    42: '交易条款"{title}"审核未通过',
    101: '{dealer}向您出售{goods_type}',
    102: '{dealer}向您购买{goods_type}',
    103: '您有新的订单待查收，请在10分钟内确认',
    104: '您有新的订单消息',
    105: '订单{order_no}超出保障时间，已自动释放',
    106: '{dealer}已取消订单',
    107: '{dealer}发起了申诉',
    108: '您有新的申诉消息',
    109: '客服已释放订单{order_no}',
    110: '客服已取消订单{order_no}',
    111: '{dealer}已释放订单{order_no}',
    112: '订单{order_no}超出查收时间，已自动取消',
    113: '订单{order_no}超出发卡时间，已自动取消',
    114: '{dealer}已查收，请耐心等待释放',
  },
  cardPwdType: {
    // 1: '密码',
    // 2: '图片',
    // 3: '密码和图片',
    1: '有卡密',
    2: '有卡图',
    3: '有图有卡密',
  },
  tradeType: {
    1: '交易',
    2: '充值',
    3: '提现',
  },
};
